# Generated by Django 4.2.7 on 2025-10-23 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('num_afiliacion', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ser exactamente 8 dígitos', regex='^\\d{8}$')])),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('alergias', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perfil_paciente',
            },
        ),
    ]
