# Generated by Django 4.2.7 on 2025-10-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_profesional', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Médico',
                'verbose_name_plural': 'Perfiles Médicos',
                'db_table': 'perfil_medicos',
            },
        ),
        migrations.AlterField(
            model_name='receta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='prescriptions.perfilmedico'),
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
