# Generated by Django 4.2.7 on 2025-10-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_perfilmedico_alter_receta_medico_delete_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmedico',
            name='activo',
        ),
    ]
