# Generated by Django 4.2.7 on 2025-10-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_perfilmedico_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='activa',
        ),
    ]
