# Generated by Django 4.2.7 on 2025-10-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_receta_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosEmail',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=250)),
                ('tipo_email', models.CharField(choices=[('PDF', 'PDF'), ('PASSWORD', 'Password')], max_length=10)),
                ('asunto', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error')], max_length=10)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_email', to='prescriptions.receta')),
            ],
            options={
                'verbose_name': 'Envío de Email',
                'verbose_name_plural': 'Envíos de Email',
                'db_table': 'envios_email',
            },
        ),
    ]
